#!/bin/bash

YNH_HELPERS_VERSION=2.1
source /usr/share/yunohost/helpers

user="$1"
app="$(basename $0 | cut -d- -f 2-)" # Extract the app name from the script name, which is supposed to be something like "50-app_id"
enable_user_home=$(ynh_app_setting_get --app="$app" --key="enable_user_home")

if [ $enable_user_home -eq 1 ]; then
    mkdir -p /home/$user/$app_home
    chown "$user:$user" /home/$user/$app_home
    setfacl --recursive --modify g:$app:rwX,d:g:$app:rwX,u:$user:rwX,d:u:$user:rwX "/home/$user/$app_home" || true
fi
