#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

user="$1"
app="$(basename $0 | cut -d- -f 2-)" # Extract the app name from the script name, which is supposed to be something like "50-app_id"
install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)
php_version=$(ynh_app_setting_get --app=$app --key=php_version)

exec_occ user:delete $user
